# tox setup
task_template: &TASK_TEMPLATE
  tox_install_script:
    - python -m pip install --upgrade pip
    - pip install tox

default_python_container: &DEFAULT_PYTHON_CONTAINER
  container:
    image: python:3.7-slim
    
test_task:
  << : *TASK_TEMPLATE
  matrix:
    - name: test python 3.8
      container: {image: "python:3.8-slim"}
      test_script: tox -e py38
    - name: test python 3.7
      container: {image: "python:3.7-slim"}
      test_script: tox -e py37
    - name: test python 3.6
      container: {image: "python:3.6-slim"}
      test_script: tox -e py36

lint_task:
  << : *DEFAULT_PYTHON_CONTAINER
  << : *TASK_TEMPLATE
  script: tox -e flake8

format_task:
  << : *DEFAULT_PYTHON_CONTAINER
  << : *TASK_TEMPLATE
  script: tox -e black

typing_task:
  << : *DEFAULT_PYTHON_CONTAINER
  << : *TASK_TEMPLATE  
  script: tox -e mypy
